### ISSUE TITLE
Pressing Escape in the TUI Settings panel crashes the TUI

### ISSUE THREAD

**Issue by alnlarsen** [StefanHolst/opentap-tui#158]
Should be simple to fix:

```
2024-06-19 10:18:50.716633 ; TUI            ; Debug       ; KeyNotFoundException: The given key '' was not present in the dictionary.
2024-06-19 10:18:50.730996 ; TUI            ; Debug       ;     at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
2024-06-19 10:18:50.731006 ; TUI            ; Debug       ;     at Terminal.Gui.View.RefreshColorScheme() in /home/alex/repos/opentap-tui/gui.cs/Terminal.Gui/Core/View.cs:line 1453
2024-06-19 10:18:50.731010 ; TUI            ; Debug       ;     at Terminal.Gui.Application.RefreshColorSchemes() in /home/alex/repos/opentap-tui/gui.cs/Terminal.Gui/Core/Application.cs:line 1147
2024-06-19 10:18:50.731014 ; TUI            ; Debug       ;     at OpenTap.Tui.TuiSettings.LoadSettings() in /home/alex/repos/opentap-tui/OpenTAP.TUI/TuiSettings.cs:line 224
2024-06-19 10:18:50.731018 ; TUI            ; Debug       ;     at OpenTap.Tui.Windows.ComponentSettingsWindow.ProcessKey(KeyEvent keyEvent) in /home/alex/repos/opentap-tui/OpenTAP.TUI/Windows/ComponentSettingsWindow.cs:line 31
2024-06-19 10:18:50.731022 ; TUI            ; Debug       ;     at Terminal.Gui.Application.ProcessKeyEvent(KeyEvent ke) in /home/alex/repos/opentap-tui/gui.cs/Terminal.Gui/Core/Application.cs:line 544
2024-06-19 10:18:50.731025 ; TUI            ; Debug       ;     at Terminal.Gui.NetDriver.ProcessInput(InputResult inputEvent) in /home/alex/repos/opentap-tui/gui.cs/Terminal.Gui/ConsoleDrivers/NetDriver.cs:line 1205
2024-06-19 10:18:50.731039 ; TUI            ; Debug       ;     at Terminal.Gui.NetDriver.<PrepareToRun>b__86_0(InputResult e) in /home/alex/repos/opentap-tui/gui.cs/Terminal.Gui/ConsoleDrivers/NetDriver.cs:line 1184
2024-06-19 10:18:50.731043 ; TUI            ; Debug       ;     at Terminal.Gui.NetMainLoop.Terminal.Gui.IMainLoopDriver.MainIteration() in /home/alex/repos/opentap-tui/gui.cs/Terminal.Gui/ConsoleDrivers/NetDriver.cs:line 1537
2024-06-19 10:18:50.731047 ; TUI            ; Debug       ;     at Terminal.Gui.MainLoop.MainIteration() in /home/alex/repos/opentap-tui/gui.cs/Terminal.Gui/Core/MainLoop.cs:line 308
2024-06-19 10:18:50.731051 ; TUI            ; Debug       ;     at Terminal.Gui.Application.RunMainLoopIteration(RunState& state, Boolean wait, Boolean& firstIteration) in /home/alex/repos/opentap-tui/gui.cs/Terminal.Gui/Core/App
lication.cs:line 1201
2024-06-19 10:18:50.731055 ; TUI            ; Debug       ;     at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait) in /home/alex/repos/opentap-tui/gui.cs/Terminal.Gui/Core/Application.cs:line 1181
2024-06-19 10:18:50.731059 ; TUI            ; Debug       ;     at Terminal.Gui.Application.Run(Toplevel view, Func`2 errorHandler) in /home/alex/repos/opentap-tui/gui.cs/Terminal.Gui/Core/Application.cs:line 1391
2024-06-19 10:18:50.731062 ; TUI            ; Debug       ;     at OpenTap.Tui.TUI.<>c__DisplayClass22_3.<TuiExecute>b__16() in /home/alex/repos/opentap-tui/OpenTAP.TUI/OpenTAP.TUI.cs:line 308
2024-06-19 10:18:50.731066 ; TUI            ; Debug       ;     at Terminal.Gui.MenuBar.<>c__DisplayClass42_0.<Run>b__0() in /home/alex/repos/opentap-tui/gui.cs/Terminal.Gui/Views/Menu.cs:line 1170
2024-06-19 10:18:50.731078 ; TUI            ; Debug       ;     at Terminal.Gui.MainLoop.RunIdle() in /home/alex/repos/opentap-tui/gui.cs/Terminal.Gui/Core/MainLoop.cs:line 264
2024-06-19 10:18:50.731082 ; TUI            ; Debug       ;     at Terminal.Gui.MainLoop.MainIteration() in /home/alex/repos/opentap-tui/gui.cs/Terminal.Gui/Core/MainLoop.cs:line 315
2024-06-19 10:18:50.731086 ; TUI            ; Debug       ;     at Terminal.Gui.Application.RunMainLoopIteration(RunState& state, Boolean wait, Boolean& firstIteration) in /home/alex/repos/opentap-tui/gui.cs/Terminal.Gui/Core/App
lication.cs:line 1201
2024-06-19 10:18:50.731092 ; TUI            ; Debug       ;     at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait) in /home/alex/repos/opentap-tui/gui.cs/Terminal.Gui/Core/Application.cs:line 1181
2024-06-19 10:18:50.731099 ; TUI            ; Debug       ;     at Terminal.Gui.Application.Run(Toplevel view, Func`2 errorHandler) in /home/alex/repos/opentap-tui/gui.cs/Terminal.Gui/Core/Application.cs:line 1391
2024-06-19 10:18:50.731102 ; TUI            ; Debug       ;     at OpenTap.Tui.TUI.TuiExecute(CancellationToken cancellationToken) in /home/alex/repos/opentap-tui/OpenTAP.TUI/OpenTAP.TUI.cs:line 450
2024-06-19 10:18:50.731106 ; TUI            ; Debug       ;     at OpenTap.Tui.TuiAction.Execute(CancellationToken cancellationToken) in /home/alex/repos/opentap-tui/OpenTAP.TUI/TuiAction.cs:line 72
2024-06-19 10:18:50.731924 ; TUI            ; Debug       ; Exception caught at:
2024-06-19 10:18:50.737291 ; TUI            ; Debug       ;     at Int32 Execute(System.Threading.CancellationToken) in /home/alex/repos/opentap-tui/OpenTAP.TUI/TuiAction.cs:line 72
2024-06-19 10:18:50.737348 ; TUI            ; Debug       ;     at Int32 PerformExecute(OpenTap.Cli.ICliAction, System.String[])
2024-06-19 10:18:50.737358 ; TUI            ; Debug       ;     at Int32 Execute(System.String[])
2024-06-19 10:18:50.737368 ; TUI            ; Debug       ;     at Void Execute()
2024-06-19 10:18:50.737401 ; TUI            ; Debug       ;     ...
2024-06-19 10:18:50.738549 ; CLI            ; Debug       ; CLI action returned exit code: 0 [16.3 s]
```

**Comment by StefanHolst** [comment]
Fixed on main
