### ISSUE TITLE
Collection was modified error

### ISSUE THREAD

**Issue by rmadsen-ks** [StefanHolst/opentap-tui#53]
We fixed this once, but it happened again.

```
2022-08-05 14:57:01.202483 ; INST           ; Information ; Resource "INST" closed. [224 us]
2022-08-05 14:57:01.202616 ; PyPowerAnalyzer ; Information ; Device PSU closed
2022-08-05 14:57:01.203059 ; PyPowerAnalyzer ; Information ; Resource "PyPowerAnalyzer" closed. [799 us]
2022-08-05 14:57:01.203232 ; DUT            ; Information ; DUT Closed
2022-08-05 14:57:01.203277 ; PyCSV          ; Information ; Resource "PyCSV" closed. [1.01 ms]
2022-08-05 14:57:01.203297 ; DUT            ; Information ; Resource "DUT" closed. [880 us]
2022-08-05 14:57:01.203896 ; TUI            ; Error       ; See session log for more information.
2022-08-05 14:57:01.206636 ; TUI            ; Debug       ; InvalidOperationException: Collection was modified; enumeration operation may not execute.
2022-08-05 14:57:01.208939 ; TUI            ; Debug       ;     at Terminal.Gui.View.Redraw(Rect bounds)
2022-08-05 14:57:01.208943 ; TUI            ; Debug       ;     at Terminal.Gui.View.Redraw(Rect bounds)
2022-08-05 14:57:01.208943 ; TUI            ; Debug       ;     at Terminal.Gui.Window.Redraw(Rect bounds)
2022-08-05 14:57:01.208944 ; TUI            ; Debug       ;     at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait)
2022-08-05 14:57:01.208945 ; TUI            ; Debug       ;     at Terminal.Gui.Application.Run(Toplevel view, Func`2 errorHandler)
2022-08-05 14:57:01.208946 ; TUI            ; Debug       ;     at OpenTap.Tui.TUI.TuiExecute(CancellationToken cancellationToken)
2022-08-05 14:57:01.208946 ; TUI            ; Debug       ;     at OpenTap.Tui.TuiAction.Execute(CancellationToken cancellationToken)
2022-08-05 14:57:01.209248 ; TUI            ; Debug       ; Exception caught at:
2022-08-05 14:57:01.211039 ; TUI            ; Debug       ;     at Int32 Execute(System.Threading.CancellationToken)
2022-08-05 14:57:01.211058 ; TUI            ; Debug       ;     at Int32 PerformExecute(OpenTap.Cli.ICliAction, System.String[])
2022-08-05 14:57:01.211062 ; TUI            ; Debug       ;     at Int32 Execute(System.String[])
2022-08-05 14:57:01.211065 ; TUI            ; Debug       ;     at Void Execute()
```

**Comment by rmadsen-ks** [comment]
Nvm, this issue is still open.

#10
